module dsms {

	interface ClinicService{
		string createNRecord(in string firstName, in string lastName, in string description, in string status, in string badgeID);
		string createDRecord(in string firstName, in string lastName, in string address, in string lastDate, in string lastLocation, in string status, in string badgeID);
		string getRecordCounts(in string badgeID);
		string editCRecord (in string lastName, in string recordID, in string newStatus, in string badgeID);
		string transferRecord(in string badgeId, in string recordId, in string remoteServerName);
		};
};
