module dsms {

	interface ClinicService{
		string createNRecord(in string firstName, in string lastName, in string designation, in string status, in string managerID);
		string createDRecord(in string firstName, in string fieldName, in string address, in string phone, in string location, in string status, in string managerID);
		string getRecordCounts(in string managerID);
		string editRecord (in string lastName, in string recordID, in string newValue, in string managerID);
		string transferRecord(in string managerId, in string recordId, in string remoteServerName);
		};
};
