package FrontEndApp;


/**
* FrontEndApp/FrontEndInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEndInterface.idl
* Friday, August 5, 2016 10:33:16 o'clock AM EDT
*/

public interface FrontEndInterface extends FrontEndInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FrontEndInterface
