package FrontEndApp;


/**
* FrontEndApp/FrontEndInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEndInterface.idl
* Friday, August 5, 2016 10:33:16 o'clock AM EDT
*/

public interface FrontEndInterfaceOperations 
{
  String exectuteOperation (String method, String managerID, String firstName, String lastName, String address, String phone, String specialization, String location, String designation, String status, String statusDate, String recordID, String fieldName, String newValue, String remoteClinicServerName);
} // interface FrontEndInterfaceOperations
